// vault-github.js - GitHub Auto-Sync Integration
// Automatically commits dissident-config.json to GitHub on vault changes

class VaultGitHub {
    constructor(token, owner = 'slothyproject', repo = 'Tokens-Vault') {
        this.token = token;
        this.owner = owner;
        this.repo = repo;
        this.baseUrl = 'https://api.github.com';
    }

    // Make authenticated API request
    async apiRequest(endpoint, options = {}) {
        const url = `${this.baseUrl}${endpoint}`;
        const response = await fetch(url, {
            ...options,
            headers: {
                'Authorization': `token ${this.token}`,
                'Accept': 'application/vnd.github.v3+json',
                'Content-Type': 'application/json',
                ...options.headers
            }
        });

        if (!response.ok) {
            const error = await response.json();
            throw new Error(error.message || `GitHub API error: ${response.status}`);
        }

        return response.json();
    }

    // Get current file content and SHA
    async getFile(path, branch = 'main') {
        try {
            const data = await this.apiRequest(
                `/repos/${this.owner}/${this.repo}/contents/${path}?ref=${branch}`
            );
            return {
                content: atob(data.content),
                sha: data.sha
            };
        } catch (error) {
            if (error.message.includes('404')) {
                return null; // File doesn't exist
            }
            throw error;
        }
    }

    // Create or update file
    async commitFile(path, content, message, branch = 'main') {
        // Check if file exists
        const existing = await this.getFile(path, branch);
        
        const body = {
            message: message,
            content: btoa(content),
            branch: branch
        };

        if (existing) {
            body.sha = existing.sha;
        }

        return this.apiRequest(
            `/repos/${this.owner}/${this.repo}/contents/${path}`,
            {
                method: 'PUT',
                body: JSON.stringify(body)
            }
        );
    }

    // Generate commit message
    generateCommitMessage(changes, serviceName) {
        const timestamp = new Date().toISOString().replace('T', ' ').substring(0, 19);
        const changeList = changes.map(c => c.variable).join(', ');
        
        return `Vault Sync: ${timestamp}

Updated: ${changeList}
Service: ${serviceName}

Auto-generated by Dissident Token Vault`;
    }

    // Sync config to GitHub
    async syncConfig(configJson, changes, serviceName) {
        const content = JSON.stringify(configJson, null, 2);
        const message = this.generateCommitMessage(changes, serviceName);
        
        try {
            const result = await this.commitFile(
                'dissident-config.json',
                content,
                message
            );
            
            return {
                success: true,
                commit: result.commit.sha,
                url: result.commit.html_url
            };
        } catch (error) {
            return {
                success: false,
                error: error.message
            };
        }
    }

    // Validate token
    async validateToken() {
        try {
            const user = await this.apiRequest('/user');
            return {
                valid: true,
                username: user.login,
                reposUrl: user.repos_url
            };
        } catch (error) {
            return {
                valid: false,
                error: error.message
            };
        }
    }

    // Get repository info
    async getRepoInfo() {
        try {
            const repo = await this.apiRequest(`/repos/${this.owner}/${this.repo}`);
            return {
                exists: true,
                name: repo.name,
                defaultBranch: repo.default_branch,
                url: repo.html_url
            };
        } catch (error) {
            return {
                exists: false,
                error: error.message
            };
        }
    }

    // Create webhook for Railway (if needed)
    async createWebhook(config) {
        const body = {
            name: 'web',
            active: true,
            events: ['push'],
            config: {
                url: config.webhookUrl,
                content_type: 'json'
            }
        };

        return this.apiRequest(
            `/repos/${this.owner}/${this.repo}/hooks`,
            {
                method: 'POST',
                body: JSON.stringify(body)
            }
        );
    }
}

// Global GitHub sync manager
const GitHubSync = {
    client: null,
    enabled: false,

    // Initialize from stored token
    initialize() {
        const token = VaultData.getGitHubToken();
        if (token) {
            this.client = new VaultGitHub(token);
            this.enabled = true;
            return true;
        }
        return false;
    },

    // Sync on vault change
    async syncOnChange(vaultData, servicesConfig, changes, serviceName) {
        if (!this.enabled || !this.client) {
            console.log('GitHub sync disabled');
            return { skipped: true };
        }

        // Generate config
        const config = VaultSyncManager.syncToConfig(vaultData, servicesConfig);
        
        try {
            const result = await this.client.syncConfig(config, changes, serviceName);
            
            if (result.success) {
                console.log('Synced to GitHub:', result.commit);
                return { success: true, commit: result.commit };
            } else {
                console.error('GitHub sync failed:', result.error);
                return { success: false, error: result.error };
            }
        } catch (error) {
            console.error('GitHub sync error:', error);
            return { success: false, error: error.message };
        }
    },

    // Test connection
    async testConnection() {
        if (!this.client) {
            return { valid: false, error: 'Not initialized' };
        }
        return this.client.validateToken();
    }
};

// Export
window.VaultGitHub = VaultGitHub;
window.GitHubSync = GitHubSync;
